on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: iad1-shared-e1-21.dreamhost.com
        protocol: sftp
        port: 22
        username: dh_gkeg59
        password: ${{ secrets.password }}
        server-dir: dragoncurvetutoring.org/
        exclude: |
          **/.git*
          **/.git*/**
