on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Deploy"
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.server }}
        remote-user: ${{ secrets.username }}
        remote-password: ${{ secrets.password }}
        remote-path: "/test"

